name: build analyze, scan todo application
on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # Disabling shallow clone is recommended for improving relevancy of reporting

    - name: Run SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=Shrikumar-Udupa_todo-backend
          -Dsonar.organization=cloudkubesec
          -Dsonar.projectName=todo-backend 

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache-dependency-path: backend/package-lock.json
    - run: npm install --prefix backend/

    - name: OWASP Depcheck
      uses: dependency-check/Dependency-Check_Action@main
      id: Depcheck
      with:
        project: 'test'
        path: '.'
        format: 'HTML'
        out: 'reports' # this is the default, no need to specify unless you wish to override it
        args: >
          --enableRetired
    - name: Upload Test results
      uses: actions/upload-artifact@master
      with:
          name: Depcheck report
          path: ${{github.workspace}}/reports

    - name: Run Trivy vulnerability scanner in repo mode (FS Scan)
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Clean install dependencies and build
      run: pwd && ls -lrth
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image using dockerfile and push to dockerhub
      uses: docker/build-push-action@v5
      with:
        context: .
        file: backend/Dockerfile
        push: true
        tags: |
            shrikumarudupa/todo-backend:${{ github.run_number }}
            shrikumarudupa/todo-backend:latest

    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: shrikumarudupa/todo-backend:latest
        severity: HIGH,CRITICAL
        format: table # You can use other formats like 'json' or 'sarif'
        ignore-unfixed: true # Optional: ignores vulnerabilities without a fix        
